### ISSUE TITLE
Unable to add GenomicMaps

### ISSUE THREAD

**Issue by aalexandersson** [kdyrhage/GenomicMaps.jl#1]
The example code begins with

```
using GenomicAnnotations
using GenomicMaps
```

which means that the two packages must first be installed. I am unable to install GenomicMaps on Julia 1.1.0 on Windows and Linux. 

```
(v1.1) pkg> add GenomicMaps
ERROR: The following package names could not be resolved:
 * GenomicMaps (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```
The error message is the same under both OS. Below is the version info for Windows.

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, nehalem)
Environment:
  JULIA_EDITOR = "C:\Users\aalexandersson\AppData\Local\atom\app-1.29.0\atom.exe" -a
  JULIA_NUM_THREADS = 4
```

**Comment by kdyrhage** [comment]
GenomicMaps is not registered in METADATA yet, use
```julia
pkg> clone https://github.com/kdyrhage/GenomicMaps.jl.git
```
#https://github.com/JuliaLang/METADATA.jl/pull/21574

**Comment by aalexandersson** [comment]
Thank you, I can now do this:

```
using GenomicAnnotations
using GenomicMaps
```

I cannot reproduce the graph. It seems that three files are required and missing:

```
chr = readgbk("GCA_000005845.2_ASM584v2_genomic.gbff.gz")[1]
addinterproscan!(chr, "interproresults.tsv")
addcogs!(chr, "cogresults.tsv")
```

Thank you again. 
Anders

**Comment by kdyrhage** [comment]
Yes, I only provided an example of how the code might look, no example data. The only thing you need is an annotation file in GenBank format ("GCA_000005845.2_ASM584v2_genomic.gbff.gz" in the example, which can be found [here](https://www.ncbi.nlm.nih.gov/assembly/GCF_000005845.2/)). Apart from that it's up to you what kind of data you want to display.

**Comment by kdyrhage** [comment]
The package has now been registered, and has an example script with example data.

**Comment by aalexandersson** [comment]
Thank you, that was very helpful. I get a new error from the function drawgenome() using Linux:

`ERROR: UndefVarError: RGB not defined`

I found a fix. I added this line in order to make your code to work:

`using Colors`

Then the function creates the file ecoli.svg

**Comment by kdyrhage** [comment]
Try the latest release, I've already added `using ColorTypes` to the example script.

**Comment by aalexandersson** [comment]
Thank you. I missed that, I only looked at [GenomicMaps.jl](https://github.com/kdyrhage/GenomicMaps.jl).
